### ISSUE TITLE
http update

### ISSUE THREAD

**Issue by PaulSoderlind** [sbnicar/BeaData.jl#20]
BeaData.jl is currently blocking my attempts to update to the latest http.jl version. Changing Project.toml to 

`HTTP = "^0.8.14, 0.9, 1.2"`

works well on my local machine

**Comment by stephenbnicar** [comment]
@PaulSoderlind Thanks for letting me know.  I've been neglecting this package and the CompatHelper action hasn't run in a while.  I'll make the appropriate update in the very near future.
