### ISSUE TITLE
No BEA UserID found!

### ISSUE THREAD

**Issue by ElvisCasco** [sbnicar/BeaData.jl#22]
Hi, it seems this is a nice package, however I don't know how to solve this error:

"No BEA UserID found!"

I've tried in this ways:

USER_ID = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
user_id = USER_ID

using DelimitedFiles
BEA_USER_ID = readdlm("bea_key.txt", String)[1];
UserID = readdlm("bea_key.txt", String)[1];

BEA_USER_ID = readdlm(".beadatarc", String)[1];
using BeaData

None of them works. Can you add an example using the User_ID into the code?

**Comment by stephenbnicar** [comment]
@ElvisCasco This is addressed in the documentation. If you don't have the user ID stored in a .beadatarc file in your home directory, you have to add it as a key word argument to the functions.  

Using one of your examples:
USER_ID = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
nipa116 = bea_table("NIPA", "T10106", "Q", 2015, 2018; user_id = USER_ID)
